apiVersion: v1
kind: Pod
metadata:
  name: ungdungnode
  labels:
    name: ungdungnode
spec:
  containers:
  - name: ungdungnode
    image: ichte/swarmtest:node
    resources:
      limits:
        memory: "128Mi"
        cpu: "100m"
    ports:
      - containerPort: <Port>
